version: 0.2

# run-as: Linux-user-name

env:
  shell: shell-tag
  variables:
    key: "value"
    key: "value"
  parameter-store:
    key: "value"
    key: "value"
  exported-variables:
    - variable
    - variable
  secrets-manager:
    key: secret-id:json-key:version-stage:version-id
  git-credential-helper: no | yes

phases:
  install:
    run-as: Linux-user-name
    runtime-versions:
      runtime: version
    commands:
      - command
  pre_build:
    # same as install
  build:
    # same as install
  post_build:
    commands:
      - abuild checksum  # From https://wiki.alpinelinux.org/wiki/APKBUILD_Reference#md5sums.2Fsha256sums.2Fsha512sums

artifacts:
  files:
    - location
    - location
  name: artifact-name
  discard-paths: no | yes
  base-directory: location

